### ISSUE TITLE
Ping Issues

### ISSUE THREAD

**Issue by PsychooYT** [LevelTranic/Vine#2]
### Stack trace

This also happends with normal shreddedpaper, when normal ping is average 10-20 it goes to 35-50

### Plugin and Datapack List

.

### Configuration files

.

### Actions to reproduce (if known)

.

### Vine version

Current Vine Server Version: 1.20.6-DEV-bc6f8e3 (MC: 1.20.6)*
* You are running the latest version
Previous: 1.20.6-DEV-f9292d2 (MC: 1.20.6)

### Other

.

**Comment by 404Setup** [comment]
Yes, this is a problem, when I test it on my folia server, the ping is usually 0ms, but on the shreddedpaper server it starts at 15ms and slowly increases.
You can turn on `use-alternate-keepalive` in `purpur.yml` to alleviate this a bit, but don't take it as a complete fix.
I was able to barely keep the ping at 14ms-21ms with `tps-catchup` and `use-alternate-keepalive` turned on, and these tests were all done on my own computer. I will still be looking for the cause of this problem.
